//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ElFartas.InstantEnglish.Interfaces;

namespace ElFartas.InstantEnglish.SqlDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categories: ICategory
    {
        public Categories()
        {
            this.Items = new HashSet<Items>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Difficulty { get; set; }
    
        public virtual ICollection<Items> Items { get; set; }
    }
}
