//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ElFartas.InstantEnglish.Interfaces;

namespace ElFartas.InstantEnglish.SqlDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items: IItem
    {
        public Items()
        {
            this.Words = new HashSet<Words>();
            this.Stats = new HashSet<Stats>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public byte[] Image { get; set; }
        public int CategoryId { get; set; }
    
        public virtual Categories Category { get; set; }
        public virtual ICollection<Words> Words { get; set; }
        public virtual ICollection<Stats> Stats { get; set; }
    }
}
