//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ElFartas.InstantEnglish.Interfaces;

namespace ElFartas.InstantEnglish.SqlDataAccess
{
    using System;
    using System.Collections.Generic;

    public partial class Users : IUser
    {
        public Users()
        {
            this.Stats = new HashSet<Stats>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Stats> Stats { get; set; }
    }
}
